#!/usr/bin/bash

if [[ -z $(pgrep -x "firefox") ]]
then
				firefox 2>&1 /dev/null  &
fi
if [[ -z  $(pgrep -x "thunderbird") ]]
then
				thunderbird 2>&1 /dev/null &
fi
if [[ -z $(pgrep -x "obsidian") ]]
then
				flatpak run md.obsidian.Obsidian 2>&1 /dev/null &
fi

killall slack 2>&1 /dev/null
flatpak run com.slack.Slack 2>&1 /dev/null &
