#!/usr/bin/bash

res=$(curl -s http://dev.joaoporta.tech:8080/timetracker)

str=$(echo $res | jq -r '.TotalToday')
working=$(echo $res | jq -r '.IsWorking')

if [ $working = "true" ]; then
		echo "%{F#a6e3a1}$str"
else
		echo "%{F#f38ba8}$str"
fi

